apiVersion: apps/v1
kind: Deployment
metadata:
  name: findadoctor-frontend
  labels:
    app: findadoctor-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: findadoctor-frontend
  template:
    metadata:
      labels:
        app: findadoctor-frontend
    spec:
      containers:
      - name: findadoctor-frontend
        image: mbilalmehmood/findadoctor-frontend:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://findadoctor-backend-service:5000/api"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"