apiVersion: v1
kind: Service
metadata:
  name: findadoctor-frontend-service
spec:
  type: NodePort
  selector:
    app: findadoctor-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080