name: Build and Deploy FindaDoctor

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker to use Minikube's daemon (Windows PowerShell)
        shell: powershell
        run: |
          Write-Host "Configuring Docker to use Minikube's daemon..."
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: 🔍 Check if Docker secrets are set (PowerShell)
        shell: powershell
        run: |
          if (-not $env:DOCKER_USERNAME) {
            Write-Host "!!!!DOCKER_USERNAME is NOT set!!!!"
          } else {
            Write-Host "DOCKER_USERNAME is set."
          }

          if (-not $env:DOCKER_PASSWORD) {
            Write-Host "!!!!DOCKER_PASSWORD is NOT set!!!!"
          } else {
            Write-Host "DOCKER_PASSWORD is set."
          }
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Backend Docker Image
        run: docker build -t mbilalmehmood/findadoctor-backend:latest ./app/FindaDoctor-BE

      - name: Build Frontend Docker Image
        run: docker build -t mbilalmehmood/findadoctor-frontend:latest ./app/FindaDoctor-FE

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Image
        run: docker push mbilalmehmood/findadoctor-backend:latest

      - name: Push Frontend Image
        run: docker push mbilalmehmood/findadoctor-frontend:latest

      - name: Deploy to Minikube
        run: |
          kubectl apply -f app/FindaDoctor-BE/kubernetes-secrets.yaml
          kubectl apply -f app/FindaDoctor-BE/deployment.yaml
          kubectl apply -f app/FindaDoctor-BE/service.yaml
          kubectl apply -f app/FindaDoctor-FE/deployment.yaml
          kubectl apply -f app/FindaDoctor-FE/service.yaml

      - name: Verify deployment
        run: |
          Write-Host "Waiting for deployments to be ready..."
          kubectl rollout status deployment/findadoctor-backend
          kubectl rollout status deployment/findadoctor-frontend
          Write-Host "Deployments are ready!"

          Write-Host "Services:"
          kubectl get services

          Write-Host "Access the frontend at:"
          minikube service findadoctor-frontend-service --url
