name: Build and Deploy FindaDoctor to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker to use Minikube's environment
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          eval $(minikube docker-env)

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Debug directory structure
      - name: Debug - List directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Repository structure:"
          find . -type d -maxdepth 2

      # Build and push Backend
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./FindaDoctor-BE
          push: true
          tags: mbilalmehmood/findadoctor-backend:latest

      # Build and push Frontend
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./FindaDoctor-FE
          push: true
          tags: mbilalmehmood/findadoctor-frontend:latest

      # Create the kubernetes-secrets.yaml file from GitHub secret before applying
      - name: Create Kubernetes secrets file
        run: printf '%s' "${{ secrets.KUBERNETES_SECRETS_YAML }}" > FindaDoctor-BE/kubernetes-secrets.yaml

      - name: Deploy to Minikube
        run: |
          kubectl apply -f FindaDoctor-BE/deployment.yaml
          kubectl apply -f FindaDoctor-BE/service.yaml
          kubectl apply -f FindaDoctor-FE/deployment.yaml
          kubectl apply -f FindaDoctor-FE/service.yaml
          kubectl apply -f FindaDoctor-BE/kubernetes-secrets.yaml

      - name: Verify deployment
        run: |
          echo "Waiting for deployments to be ready..."
          kubectl rollout status deployment/findadoctor-backend
          kubectl rollout status deployment/findadoctor-frontend
          echo "Deployments are ready!"

          echo "Services:"
          kubectl get services

          echo "Access the frontend at:"
          minikube service findadoctor-frontend-service --url