name: Build and Deploy FindaDoctor to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        eval $(minikube docker-env)

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push Backend
    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4  # Using build-push-action for better caching
      with:
        context: ./app/FindaDoctor-BE
        push: true
        tags: mbilalmehmood/findadoctor-backend:latest

    # Build and push Frontend
    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./app/FindaDoctor-FE
        push: true
        tags: mbilalmehmood/findadoctor-frontend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f app/FindaDoctor-BE/kubernetes-secrets.yaml
        kubectl apply -f app/FindaDoctor-BE/deployment.yaml
        kubectl apply -f app/FindaDoctor-BE/service.yaml
        kubectl apply -f app/FindaDoctor-FE/deployment.yaml
        kubectl apply -f app/FindaDoctor-FE/service.yaml

    - name: Verify deployment
      run: |
        echo "Waiting for deployments to be ready..."
        kubectl rollout status deployment/findadoctor-backend
        kubectl rollout status deployment/findadoctor-frontend
        echo "Deployments are ready!"
        
        echo "Services:"
        kubectl get services
        
        echo "Access the frontend at:"
        minikube service findadoctor-frontend-service --url