apiVersion: apps/v1
kind: Deployment
metadata:
  name: findadoctor-backend
  labels:
    app: findadoctor-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: findadoctor-backend
  template:
    metadata:
      labels:
        app: findadoctor-backend
    spec:
      containers:
      - name: findadoctor-backend
        image: mbilalmehmood/findadoctor-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: token
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: cloudinary-secret
              key: cloud_name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: cloudinary-secret
              key: api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: cloudinary-secret
              key: api_secret
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: user
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: email-secret
              key: pass
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"