apiVersion: apps/v1
kind: Deployment
metadata:
  name: findadoctor-backend
  labels:
    app: findadoctor-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: findadoctor-backend
  template:
    metadata:
      labels:
        app: findadoctor-backend
    spec:
      containers:
      - name: findadoctor-backend
        image: mbilalmehmood/findadoctor-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: MONGODB_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: JWT_SECRET
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: CLOUDINARY_CLOUD_NAME
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: CLOUDINARY_API_KEY
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: CLOUDINARY_API_SECRET
        - name: EMAIL_USER
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: EMAIL_USER
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: STRIPE_SECRET_KEY
        - name: EMAIL_PASS
          valueFrom:
            secretKeyRef:
              name: findadoctor-backend-secrets
              key: EMAIL_PASS
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"